#C:\SIRA\SIRA\docker-compose.override.yml
# docker-compose.override.yml (Desarrollo)
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: npm run dev
    ports:
      - "3001:3001"
      - "9229:9229"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - TZ=America/Mexico_City

  frontend:
    build:
      context: ./sira-front
      dockerfile: Dockerfile.dev
    env_file:
      - ./sira-front/.env.docker
    ports:
      - "5173:5173"
    volumes:
      - ./sira-front:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - TZ=America/Mexico_City
    # depends_on:
    #   - backend
