# /SIRA/docker-compose.yml

services:
  # Servicio para el backend (sin cambios)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  # Servicio para el frontend en modo desarrollo (ACTUALIZADO)
  frontend-dev:
    build:
      context: ./sira-front
      dockerfile: Dockerfile.dev
    # --- LÍNEA AÑADIDA ---
    # Carga las variables de entorno específicas para Docker
    env_file:
      - ./sira-front/.env.docker
    # ----------------------
    volumes:
      - ./sira-front:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true