# /SIRA/docker-compose.yml

services:
  # Servicio para el backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  # Servicio para el frontend en modo desarrollo
  frontend-dev:
    build:
      # CAMBIO CLAVE: El contexto ahora apunta explícitamente a la carpeta del frontend
      context: ./sira-front
      dockerfile: Dockerfile.dev
    volumes:
      - ./sira-front:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true