# SIRA/backend/Dockerfile.dev

# 1. Usar una imagen oficial de Node.js como base
FROM node:18-alpine

# 2. Establecer el directorio de trabajo
WORKDIR /app

# 3. Copiar los archivos de dependencias
COPY package*.json ./

# 4. Instala TODAS las dependencias (incluyendo nodemon)
RUN npm ci

# 5. Copiar el resto del código
COPY . .

# 6. Exponer el puerto
EXPOSE 3001

# 7. Comando por defecto (será sobrescrito por el docker-compose.override.yml)
CMD [ "nodemon", "app.js" ]