# SIRA/backend/Dockerfile.dev

# Se mantiene la imagen base de Alpine por su ligereza
FROM node:22-alpine
WORKDIR /app
ENV NODE_ENV=development
COPY package*.json ./
RUN npm ci
COPY . .
EXPOSE 3001 9229
CMD ["npm","run","dev"]