version: '3.8'

services:
  # Producción: build estático servido con Nginx en el puerto 3000
  web:
    build:
      context: .
      dockerfile: Dockerfile   # este nuevo archivo
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production

  # Desarrollo: Vite + hot-reload en el puerto 5173
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
