services:
  web:
    # Indica que use el Dockerfile.dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    # Volúmenes: tu código + aislamos node_modules del host
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true