# C:\SIRA\SIRA\.github\workflows\deploy-frontend-staging.yml

# .github/workflows/deploy-frontend-staging.yml

name: Desplegar Frontend a Staging

on:
  push:
    branches:
      - develop # Se activa con cada push a la rama 'develop'
    paths:
      - 'sira-front/**' # Pero solo si los cambios ocurrieron en la carpeta 'sira-front'

env:
  PROJECT_ID: sira-grupo-ig
  REGION: us-central1
  SERVICE_NAME: sira-web-stg
  REPO_NAME: sira-artifacts

jobs:
  deploy:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Autenticar con Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/386605754193/locations/global/workloadIdentityPools/sira-github-pool/providers/sira-github-provider'
          service_account: 'sa-sira-deployer@sira-grupo-ig.iam.gserviceaccount.com'

      - name: Configurar gcloud
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configurar Docker
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Construir y Subir Imagen
        run: |-
          docker build \
            --build-arg VITE_API_URL="${{ secrets.STAGING_API_URL }}" \
            -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
            ./sira-front
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

      - name: Desplegar a Cloud Run
        run: |-
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}" \
            --region="${{ env.REGION }}" \
            --platform="managed" \
            --allow-unauthenticated